name: timezone
version: 0.8.1
description: Time zone database and time zone aware DateTime.
repository: https://github.com/srawlins/timezone
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  path: ^1.8.1
  platform: ^3.1.0
#  http: ^0.13.4
dev_dependencies:
  args: any
  file: ^6.1.2
  glob: ^2.1.0
  lints: ^2.0.0
  logging: any
  test: ^1.21.4
